### ISSUE TITLE
Benchmark_inference

### ISSUE THREAD

**Issue by erlebach** [fkodom/yet-another-retnet#18] opened 2023-11-06 19:01 UTC
I don't quite understand the line: 
```
            transformer_result = benchmark(transformer, x[:, -1:], start_pos=seq_length - 1)
```
I timed it and also timed the following: 
```
            transformer_result = benchmark(transformer, x[:, 0:1], start_pos=0)
```
The longer the seq_length, I was expecting the timings to become more and more disparate. But that isn't the case. The second call gave a throughput of approximately 50% of the throughput of the first call. Why would that be? I believe I have some kind of misunderstanding. Thanks.

**Comment by fkodom** [comment] 2023-11-07 15:08
@erlebach I'm not able to reproduce the 50% throughput difference you described.

The `TransformerLM` model is using a KV cache, which stores the (key, value) projections from previous iterations for greater efficiency.  The larger your `start_pos` is, the more tokens from the cache are input to the model.  With `start_pos=seq_length - 1`, you should see the Transformer throughput proportional to `(1 / seq_length)`.

My local timings using the provided benchmark script:
```python
transformer_result = benchmark(transformer, x[:, -1:], start_pos=seq_length - 1)
```
```
Benchmarking inference throughput...
seq_length: 2048
RetNet throughput: 169.198 tokens/s
Transformer throughput: 32.561 tokens/s
seq_length: 3072
RetNet throughput: 168.538 tokens/s
Transformer throughput: 22.192 tokens/s
seq_length: 4096
RetNet throughput: 169.317 tokens/s
Transformer throughput: 16.867 tokens/s
seq_length: 5120
RetNet throughput: 169.625 tokens/s
Transformer throughput: 13.653 tokens/s
seq_length: 6144
RetNet throughput: 169.368 tokens/s
Transformer throughput: 11.403 tokens/s
```

In the second case with `start_pos=0`, inference will **always** [use a single token from the KV cache](https://github.com/fkodom/yet-another-retnet/blob/485a10a1043c7f7b25942867b6b11c1c247c2e90/scripts/benchmark_inference.py#L66-L68).  For that reason, the inference latency should now be independent of the sequence length -- confirmed by the benchmark script, where throughput is now much higher and roughly constant.

```python
transformer_result = benchmark(transformer, x[:, 0:1], start_pos=0)
```

```
Benchmarking inference throughput...
seq_length: 2048
RetNet throughput: 168.090 tokens/s
Transformer throughput: 202.074 tokens/s
seq_length: 3072
RetNet throughput: 168.641 tokens/s
Transformer throughput: 192.910 tokens/s
seq_length: 4096
RetNet throughput: 168.724 tokens/s
Transformer throughput: 202.399 tokens/s
seq_length: 5120
RetNet throughput: 168.665 tokens/s
Transformer throughput: 202.023 tokens/s
seq_length: 6144
RetNet throughput: 168.609 tokens/s
Transformer throughput: 199.622 tokens/s
```

**Comment by fkodom** [comment] 2023-11-07 15:34
> In the second case with start_pos=0, inference will always [use a single token from the KV cache](https://github.com/fkodom/yet-another-retnet/blob/485a10a1043c7f7b25942867b6b11c1c247c2e90/scripts/benchmark_inference.py#L66-L68).

Note - this is incorrect usage of the transformer model.  It may be faster, but will not give similar outputs.

**Comment by fkodom** [comment] 2023-11-08 19:15
@erlebach Closing for now, but feel free to add more questions if you have any.

**Closed as completed by fkodom** 2023-11-08 19:15 UTC
